language: go
sudo: false
matrix:
  include:
    - go: 1.11.x
      env:
        - LATEST=true
        - IMPPATH=github.com/hedzr/ini-op
  #  - go: 1.x
  #  - go: tip
  # allow_failures:
  #  - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - if [ ! -d bin ]; then mkdir bin; fi
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  #- go vet $(go list ./... | grep -v /vendor/)
  #- go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then cd cli; gox -os="linux darwin windows" -arch="amd64" -output="bin/ini-op.{{.OS}}.{{.Arch}}" -ldflags "-s -w -X ${IMPPATH}/cli_common.Buildstamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X ${IMPPATH}/cli_common.Githash=`git rev-parse --short HEAD` -X ${IMPPATH}/cli_common.GoVersion=`go version`" -verbose ./...; cd ..; fi

#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "Hedzr Yeh"
#  - git config --local user.email "hedzrz@gmail.com"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: GIM3BLLsgOIKB2xB9Uigt6/mCXG8gr0MIYJ5rHyoJzybe1uwGuf8LVK5r8+wqPIjlToZQHdLl+oMsLNV93CnHJiiMgioXgtQDLhFFwireIHTbpPEDLcqVIkLXjr62wJktkIUS8haGi+PjaSS0IEboPbDsozIpaDxufKBwSMGSg82QMlCbgc2JVjohY9wj4OijEgyeYlyQX5TcO+5ZZXxt8fS3zsAIjcTnr9P54k1P0EJ3eA17n4cJJxMrbzPv5Ku0o41OgYgTdjVr4+oWRO+xcoYSNjC0XCe+Mt/yXRRSskDs84YFflvB4HeDaW1uKYQqF1BEh1SdoHKyJQDis7wv64/BBFs/vWXEKDpZxGGaVRKbU1bF8iSgPQvnZx31/pCg0IIJAdqxy+2oPiPCuWX5fZmopxR2KOvDLC4Mnz8HLWO3CE5rEUsp9z4cmf0ilfWeIzYhgO30EuPRc5rHEdL29xxi9F+r6/uVIWhnM1L5CS50yVdvKnD00AcdMKr/B6KN6arLA9brgdpuRgGSKf4hClArpKManDRi/mqKss7JnyZZ9+3QXyr45Cr2wgdwVYIgMBYaw0HieEzfkcA7iKAfVOyMtV0QvPlPpNu47beNOXS+DDQFdbKDWchusFB4LcVrq5m/qfJaZuVTj9nQaUdOzC5fcO2fAPa/dMqFvYgA9w=
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - bin/ini-op.windows.amd64.exe
    - bin/ini-op.darwin.amd64
    - bin/ini-op.linux.amd64
  on:
    # What to repository to build
    repo: hedzr/ini-op
    # Only build binaries for tagged commits
    tags: true
    condition: $LATEST = true

notifications:
  email:
    recipients:
      - hedzrz@gmail.com
    on_success: change
    on_failure: always
