language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  #- go vet $(go list ./... | grep -v /vendor/)
  #- go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="ini-op.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose cli/main.go; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: K94JYYm0N/BzDYzMoWjo1MrqgsWOmIb8kTiQ1/GCuTm/wHc1eUF2I9I7mej6ZMcUpxVP0yJfNHwZmcwWYq9DNnRDlq4HNwYKjJjIZDMEcVqF/DN6Muo6XCMly0OjQvy8/gRrUUFCQ771BjDysmQzQFlv2V5BbcQ1gphuWP1lyOHQ2Z40l+Ss/g5fPq11M1L44cwrveUKlX9yypQUSzGgq12+JY2W3EOIr4NttTwIJ1dVFU8SmNICcXBXy/0Ed6p5NEewJKBshyVf0RlpZjHIJElzOPqctRYSgLlru2eJbnwaZPQ/0aT6wFLPXAk9MDhp1D87GTPyIgHg0mqRAJw3Ey6X2vpL4oyn0q/kc4YVgjdk18g3fsTGqHiD20rQR6yFPv+yEidVBaiqZ7lEDoUKaU2tbJ8Gc+t0zVesPMI6AX2AXTT/ZhNgyE88LpCW9HXXQlw2UYabQiCH5LljALGQJg92lAkEEiFjU5/k3I+jtdL7A0DjFc8CHgnyeFagJga8CqkjhIPytl+vrpuxb8GQKbqR5BPfEfPZyUCs7SwVGiOp4C7Mi3+XTG9id3z+GDi8PHVsoYGQEOIWM3dcuvT2Wv8FXt/k5ITj0vDexflgHZL75L+zEM7fukCkeKnULY1V81jS2vJxXgQe+JJT2QDZJuRyDdhkbUQNHqbleiMzZR4=
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - ini-op.windows.amd64.exe
    - ini-op.darwin.amd64
    - ini-op.linux.amd64
  on:
    # What to repository to build
    repo: hedzr/ini-op
    # Only build binaries for tagged commits
    tags: true
    condition: $LATEST = true

notifications:
  email:
    recipients:
      - hedzrz@gmail.com
    on_success: change
    on_failure: always